#!/bin/bash
set -e

# Ensure we are on main branch
current_branch=$(git branch --show-current)
if [ "$current_branch" != "main" ]; then
    echo "Must be on 'main' branch to deploy. Current: $current_branch"
    exit 1
fi

echo "Building release..."
python3 scripts/build_release.py

echo "Checking out release branch..."
if git show-ref --verify --quiet refs/heads/release; then
    git checkout release
else
    git checkout --orphan release
fi

# Remove all existing tracked files in release
git rm -rf . || true

# Copy standard release artifacts to root
cp -r release/xiaofan-release-v2.1/* .

# For Antigravity users who clone this repo directly, we map agy_skill to .agents/skills/
mkdir -p .agents/skills/simulating-xiaofan
cp -r release/xiaofan-release-v2.1/agy_skill/* .agents/skills/simulating-xiaofan/

# Clean up the release folder generated by main branch
rm -rf release/

# Add a specific README for the release branch
cat << 'EOF' > README.md
# 小饭数字分身 (Xiaofan Digital Clone) - 开箱即用版

这是已编译打包完成的**最终交付产物 (Release)**。
任何人 Clone 本仓库的默认 release 分支后，可以直接拿走使用。

## 📦 产物列表

- 🤖 **Agent 开发**：去 `agent_frameworks/` 获取 CrewAI / AutoGen / OpenAI API 的配置。
- 💻 **IDE 玩家**：去 `ide_adapters/` 获取 Cursor / Cline / Windsurf 的专属规则，拖入你的工程。
- 🗣️ **纯享版**：去 `standard_prompt/` 复制文本，扔给 ChatGPT。
- 🌐 **知识库**：去 `knowledge_base/` 下载 Markdown 导入 Dify / Coze。
- ⚡ **Antigravity 原生支持**：本分支已自带 `.agents/skills/simulating-xiaofan`。如果你通过 Antigravity 的 Workspace 挂载此目录，该技能会被**自动发现并激活**，无需额外配置！

---

> ⚠️ **开发者注意 (For Developers)** 
> 当前的 `release` 分支**仅包含**由脚本编译后的“死产物”，用于对外分发。
> 如果你需要查看和修改底层源码（如 `persona/` 模块）、增加测试集或是维护 API 测试脚本，**请务必切换到 `main` 分支**：
> 
> ```bash
> git checkout main
> ```
EOF

git add .
git commit -m "chore(release): deploy automated release artifacts to release branch" || true

git checkout main
echo "Deploy complete! We are back on 'main' branch."
