#!/bin/bash
set -e

# Ensure we are on main branch
current_branch=$(git branch --show-current)
if [ "$current_branch" != "main" ]; then
    echo "Must be on 'main' branch to deploy. Current: $current_branch"
    exit 1
fi

echo "Building release..."
python3 scripts/build_release.py

echo "Checking out release branch..."
if git show-ref --verify --quiet refs/heads/release; then
    git checkout release
else
    git checkout --orphan release
fi

# Remove all existing tracked files in release
git rm -rf . || true

# Deploy release artifacts to .agents/skills/ (the standard skill path)
mkdir -p .agents/skills/xiaofan-persona
cp -r release/xiaofan-persona/* .agents/skills/xiaofan-persona/

# Clean up the release folder generated by main branch
rm -rf release/

# Add a specific README for the release branch
cat << 'EOF' > README.md
# 小饭数字分身 (Xiaofan Digital Clone) - 开箱即用版

这是已编译打包完成的**最终交付产物 (Release)**。
任何人 Clone 本仓库的默认 release 分支后，可以直接拿走使用。

## 📦 产物列表

- 🤖 **Agent Skill**：`.agents/skills/xiaofan-persona/` 包含完整的 Skill 定义（SKILL.md + Prompt_System.md + canonical_principles.md + FAILURE_MODES.md），导入任何支持 Skill 机制的 AI 客户端即可使用。


---

> ⚠️ **开发者注意 (For Developers)** 
> 当前的 `release` 分支**仅包含**由脚本编译后的“死产物”，用于对外分发。
> 如果你需要查看和修改底层源码（如 `persona/` 模块）、增加测试集或是维护 API 测试脚本，**请务必切换到 `main` 分支**：
> 
> ```bash
> git checkout main
> ```
EOF

git add .
git commit -m "chore(release): deploy automated release artifacts to release branch" || true

git checkout main
echo "Deploy complete! We are back on 'main' branch."
